FROM node:20-alpine

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .

EXPOSE 3002

ENV PORT=3002
ENV NEXT_PUBLIC_API_GATEWAY_URL=http://localhost:3000

CMD ["pnpm", "run", "dev"]
